format_version: 10
pipelines:
  pipe1:
    group: microservices
    materials:
      gitrepo:
        git: https://github.com/RichardETDL/gocd-pipelines.git
        branch: main
    stages:
      - build: # name of stage
          jobs:
            build: # name of the job
              tasks:
               - exec: # indicates type of task
                   command: bash
                   arguments:
                   - -c
                   - echo "Building app"
      - depl-dev: # name of stage
          jobs:
            build: # name of the job
              tasks:
               - exec: # indicates type of task
                   command: bash
                   arguments:
                   - -c
                   - echo "depl dev"
      - test-dev: # name of stage
          jobs:
            build: # name of the job
              tasks:
               - exec: # indicates type of task
                   command: bash
                   arguments:
                   - -c
                   - echo "test dev"
       - depl-int:
          jobs:
            build: # name of the job
              tasks:
               - exec: # indicates type of task
                   command: bash
                   arguments:
                   - -c
                   - echo "depl int"
      - test-int:
          jobs:
            build: # name of the job
              tasks:
               - exec: # indicates type of task
                   command: bash
                   arguments:
                   - -c
                   - echo "test int"
       - depl-prd:
          jobs:
            build: # name of the job
              tasks:
               - exec: # indicates type of task
                   command: bash
                   arguments:
                   - -c
                   - echo "dev prd
      - test-prd:
          jobs:
            build: # name of the job
              tasks:
               - exec: # indicates type of task
                   command: bash
                   arguments:
                   - -c
                   - echo "test prd"

